### ISSUE TITLE
Error when placing the same blocks the second time

### ISSUE THREAD

**Issue by alexdev03** [TheGaming999/BlockChanger#2]
Hi, when I set to air an area it's working fine, but when I try to place again air in the same area it gives me this error many many times:

```
java.lang.NullPointerException: null
	at com.andrei1058.bedwars.arena.mapreset.slime.BlockUpdaterLegacy.getSection(BlockChanger.java:2366) ~[?:?]
	at com.andrei1058.bedwars.arena.mapreset.slime.BlockChanger.getSection(BlockChanger.java:1458) ~[?:?]
	at com.andrei1058.bedwars.arena.mapreset.slime.BlockChanger.access$1000(BlockChanger.java:53) ~[?:?]
	at com.andrei1058.bedwars.arena.mapreset.slime.BlockChanger$SectionSetWorkload.compute(BlockChanger.java:2135) ~[?:?]
	at com.andrei1058.bedwars.arena.mapreset.slime.BlockChanger$WorkloadRunnable.run(BlockChanger.java:2042) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched_1.8.8.jar:git-PaperSpigot-445]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_352]
```

**Comment by Sandwichas** [comment]
Can you test it in a spigot server instead of paperspigot?
Also, by the same area, you mean the same exact location coordinates or within a certain region?
And are you sure that it only happens with air?

**Comment by alexdev03** [comment]
I'll test next week on normal spigot. Yes the same area, loc1 and loc2. I tried only with air, I'll test with other types of blocks.

**Comment by Sandwichas** [comment]
No follow up.
